name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mmenanno
          base_indepth: yes
          base_hireable: yes
          config_timezone: America/New_York
          repositories_affiliations: owner, collaborator, organization_member

          plugin_isocalendar: yes

          plugin_languages: yes
          plugin_languages_other: yes

          plugin_notable: yes

          plugin_achievements: yes
